ALTER TABLE MRKT_SLS_PERD 
NOCOMPRESS;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_CASH_VAL;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_R_FACTOR;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_PRCSNG_DT;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_ALOCTN_USER_ID;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_ALOCTN_STRT_TS;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_ALOCTN_END_TS;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN EST_BILNG_DT;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN BST_BILNG_DT;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_ONSCH_EST_BI24_IND;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_OFFSCH_BST_BI24_IND;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_SLS_TYP_ID;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_AUTCLC_EST_IND;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_AUTCLC_BST_IND;

ALTER TABLE MRKT_SLS_PERD 
COMPRESS;
