drop table BI24_GENRTN_STATSS;
drop table CASH_VAL_RF_HIST;
drop table CUSTM_RUL_MSTR;
drop table CUSTM_RUL_PERD;
drop table CUSTM_RUL_SKU_LIST;
drop table CUSTM_SEG_MSTR;
drop table CUSTM_SEG_PERD;
drop table DLY_BILNG_ADJSTMNT;
drop table MRKT_PERD_PARTS;
drop table MRKT_PERD_SKU_BIAS;
drop table MRKT_TRND_SLS_PERD;
drop table MRKT_TRND_SLS_PERD_SLS_TYP;
drop table SCT_FSC_OVRRD;
drop table TA_CONFIG;
drop table TA_DICT;
drop table TREND_ALLOC_HIST_DTLS;
drop table TREND_ALLOC_HIST_DTLS_LOG;
drop table TREND_OFFST;

