CREATE TABLE mps_files (
  "FILE_ID" VARCHAR2(255) NOT NULL, 
  "FILENAME" VARCHAR2(255) NOT NULL, 
  "DATA" BLOB NOT NULL, 
  "SIZE" NUMBER(19) NOT NULL, 
  "MIME_TYPE" VARCHAR2(255) NOT NULL, 
  "CREATE_TIME" TIMESTAMP NOT NULL, 
  CONSTRAINT PK_MPS_FILES PRIMARY KEY (FILE_ID));
