--------------------------------------------------------
--  File created - Wednesday-November-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTM_RUL_SKU_LIST
--------------------------------------------------------

  CREATE TABLE CUSTM_RUL_SKU_LIST 
   (	RUL_ID NUMBER, 
	SKU_ID NUMBER, 
	CREAT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER, 
	CREAT_TS DATE DEFAULT SYSDATE, 
	LAST_UPDT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER, 
	LAST_UPDT_TS DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &data_tablespace_name ;
 

   COMMENT ON COLUMN CUSTM_RUL_SKU_LIST.RUL_ID IS 'Rule Id';
 
   COMMENT ON COLUMN CUSTM_RUL_SKU_LIST.SKU_ID IS 'SKU Id contained in the rule';
 
   COMMENT ON COLUMN CUSTM_RUL_SKU_LIST.CREAT_USER_ID IS 'The user who inserted the record';
 
   COMMENT ON COLUMN CUSTM_RUL_SKU_LIST.CREAT_TS IS 'Date/timestamp of record creation';
 
   COMMENT ON COLUMN CUSTM_RUL_SKU_LIST.LAST_UPDT_USER_ID IS 'The user who last changed the record';
 
   COMMENT ON COLUMN CUSTM_RUL_SKU_LIST.LAST_UPDT_TS IS 'Date/timestamp of latest change';
--------------------------------------------------------
--  DDL for Index UK_CUSTM_RUL_SKU_LIST
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_CUSTM_RUL_SKU_LIST ON CUSTM_RUL_SKU_LIST (RUL_ID, SKU_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;
--------------------------------------------------------
--  Constraints for Table CUSTM_RUL_SKU_LIST
--------------------------------------------------------

  ALTER TABLE CUSTM_RUL_SKU_LIST MODIFY (RUL_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_SKU_LIST MODIFY (SKU_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_SKU_LIST ADD CONSTRAINT UK_CUSTM_RUL_SKU_LIST UNIQUE (RUL_ID, SKU_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;

