--------------------------------------------------------
--  File created - Wednesday-November-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTM_SEG_MSTR
--------------------------------------------------------

  CREATE TABLE CUSTM_SEG_MSTR 
   (	RUL_ID NUMBER, 
	MRKT_ID NUMBER, 
	RUL_NM VARCHAR2(50 BYTE), 
	RUL_DESC VARCHAR2(200 BYTE), 
	OFFST_LBL_ID NUMBER, 
	CATGRY_ID NUMBER, 
	SLS_CLS_CD NUMBER, 
	VEH_ID NUMBER, 
	PERD_PART NUMBER, 
	CREAT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER, 
	CREAT_TS DATE DEFAULT SYSDATE, 
	LAST_UPDT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER, 
	LAST_UPDT_TS DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &data_tablespace_name ;
 

   COMMENT ON COLUMN CUSTM_SEG_MSTR.RUL_ID IS 'Rule Id';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.MRKT_ID IS 'Market';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.RUL_NM IS 'Rule Name';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.RUL_DESC IS 'Rule Description';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.OFFST_LBL_ID IS 'Condition for offset';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.CATGRY_ID IS 'Condition for category';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.SLS_CLS_CD IS 'Condition for sales class';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.VEH_ID IS 'Condition for vehicle';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.PERD_PART IS 'Condition for period part selection (1- beginning, 2 - middle, 3 - end)';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.CREAT_USER_ID IS 'The user who inserted the record';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.CREAT_TS IS 'Date/timestamp of record creation';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.LAST_UPDT_USER_ID IS 'The user who last changed the record';
 
   COMMENT ON COLUMN CUSTM_SEG_MSTR.LAST_UPDT_TS IS 'Date/timestamp of latest change';
 
   COMMENT ON TABLE CUSTM_SEG_MSTR  IS 'Describes master data for custom segment rules';
--------------------------------------------------------
--  DDL for Index PK_CUSTM_SEG_MSTR
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CUSTM_SEG_MSTR ON CUSTM_SEG_MSTR (RUL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;
--------------------------------------------------------
--  DDL for Index UK_MOCSVP_CUSTMSEGMSTR
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_MOCSVP_CUSTMSEGMSTR ON CUSTM_SEG_MSTR (MRKT_ID, OFFST_LBL_ID, CATGRY_ID, SLS_CLS_CD, VEH_ID, PERD_PART) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;
--------------------------------------------------------
--  DDL for Index UK_MRKTRULNM_CUSTMSEGMSTR
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_MRKTRULNM_CUSTMSEGMSTR ON CUSTM_SEG_MSTR (MRKT_ID, RUL_NM) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;
--------------------------------------------------------
--  Constraints for Table CUSTM_SEG_MSTR
--------------------------------------------------------

  ALTER TABLE CUSTM_SEG_MSTR ADD CONSTRAINT CHK_CUSTM_SEG_MSTR CHECK (Perd_part in(1,2,3)) ENABLE;
 
  ALTER TABLE CUSTM_SEG_MSTR ADD CONSTRAINT PK_CUSTM_SEG_MSTR PRIMARY KEY (RUL_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;
 
  ALTER TABLE CUSTM_SEG_MSTR MODIFY (RUL_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_SEG_MSTR MODIFY (MRKT_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_SEG_MSTR MODIFY (RUL_NM NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_SEG_MSTR MODIFY (CREAT_USER_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_SEG_MSTR MODIFY (CREAT_TS NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_SEG_MSTR MODIFY (LAST_UPDT_USER_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_SEG_MSTR MODIFY (LAST_UPDT_TS NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_SEG_MSTR MODIFY (OFFST_LBL_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_SEG_MSTR ADD CONSTRAINT UK_MOCSVP_CUSTMSEGMSTR UNIQUE (MRKT_ID, OFFST_LBL_ID, CATGRY_ID, SLS_CLS_CD, VEH_ID, PERD_PART)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;
 
  ALTER TABLE CUSTM_SEG_MSTR ADD CONSTRAINT UK_MRKTRULNM_CUSTMSEGMSTR UNIQUE (MRKT_ID, RUL_NM)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;

