--------------------------------------------------------
--  File created - Wednesday-November-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTM_RUL_PERD
--------------------------------------------------------

  CREATE TABLE CUSTM_RUL_PERD 
   (CAMPGN_PERD_ID NUMBER, 
    RUL_ID NUMBER, 
    PERIOD_LIST VARCHAR2(2048 BYTE), 
    R_FACTOR NUMBER, 
    R_FACTOR_MANUAL NUMBER, 
    CASH_VALUE NUMBER,
    USE_ESTIMATE CHAR(1),
    CREAT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER, 
    CREAT_TS DATE DEFAULT sysdate, 
    LAST_UPDT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER, 
    LAST_UPDT_TS DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &data_tablespace_name ;
 

   COMMENT ON COLUMN CUSTM_RUL_PERD.CREAT_USER_ID IS 'The user who inserted the record';
 
   COMMENT ON COLUMN CUSTM_RUL_PERD.CREAT_TS IS 'Date/timestamp of record creation';
 
   COMMENT ON COLUMN CUSTM_RUL_PERD.LAST_UPDT_USER_ID IS 'The user who last changed the record';
 
   COMMENT ON COLUMN CUSTM_RUL_PERD.LAST_UPDT_TS IS 'Date/timestamp of latest change';
--------------------------------------------------------
--  DDL for Index UK_PR_CUSTMRULPERD
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_PR_CUSTMRULPERD ON CUSTM_RUL_PERD (CAMPGN_PERD_ID, RUL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;
--------------------------------------------------------
--  Constraints for Table CUSTM_RUL_PERD
--------------------------------------------------------

  ALTER TABLE CUSTM_RUL_PERD MODIFY (CAMPGN_PERD_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_PERD MODIFY (RUL_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_PERD ADD CONSTRAINT UK_PR_CUSTMRULPERD UNIQUE (CAMPGN_PERD_ID, RUL_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;

