--------------------------------------------------------
--  File created - Wednesday-November-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTM_RUL_MSTR
--------------------------------------------------------

  CREATE TABLE CUSTM_RUL_MSTR 
   (	RUL_ID NUMBER, 
	RUL_NM VARCHAR2(50 BYTE), 
	RUL_DESC VARCHAR2(200 BYTE), 
	CREAT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER, 
	CREAT_TS DATE DEFAULT SYSDATE, 
	LAST_UPDT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER, 
	LAST_UPDT_TS DATE DEFAULT sysdate, 
	MRKT_ID NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &data_tablespace_name ;
 

   COMMENT ON COLUMN CUSTM_RUL_MSTR.RUL_ID IS 'Rule Id';
 
   COMMENT ON COLUMN CUSTM_RUL_MSTR.RUL_NM IS 'Rule Name';
 
   COMMENT ON COLUMN CUSTM_RUL_MSTR.RUL_DESC IS 'Rule Description';
 
   COMMENT ON COLUMN CUSTM_RUL_MSTR.CREAT_USER_ID IS 'The user who inserted the record';
 
   COMMENT ON COLUMN CUSTM_RUL_MSTR.CREAT_TS IS 'Date/timestamp of record creation';
 
   COMMENT ON COLUMN CUSTM_RUL_MSTR.LAST_UPDT_USER_ID IS 'The user who last changed the record';
 
   COMMENT ON COLUMN CUSTM_RUL_MSTR.LAST_UPDT_TS IS 'Date/timestamp of latest change';
 
   COMMENT ON COLUMN CUSTM_RUL_MSTR.MRKT_ID IS 'Market';
 
   COMMENT ON TABLE CUSTM_RUL_MSTR  IS 'Describes master data for custom group rules';
--------------------------------------------------------
--  DDL for Index PK_CUSTM_RUL_MSTR
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CUSTM_RUL_MSTR ON CUSTM_RUL_MSTR (RUL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;
--------------------------------------------------------
--  DDL for Index UK_MRKTRULNM_CUSTMRULMSTR
--------------------------------------------------------

  CREATE UNIQUE INDEX UK_MRKTRULNM_CUSTMRULMSTR ON CUSTM_RUL_MSTR (MRKT_ID, RUL_NM) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;

--------------------------------------------------------
--  Constraints for Table CUSTM_RUL_MSTR
--------------------------------------------------------

  ALTER TABLE CUSTM_RUL_MSTR ADD CONSTRAINT PK_CUSTM_RUL_MSTR PRIMARY KEY (RUL_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;
 
  ALTER TABLE CUSTM_RUL_MSTR MODIFY (RUL_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_MSTR MODIFY (RUL_NM NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_MSTR MODIFY (CREAT_USER_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_MSTR MODIFY (CREAT_TS NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_MSTR MODIFY (LAST_UPDT_USER_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_MSTR MODIFY (LAST_UPDT_TS NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_MSTR MODIFY (MRKT_ID NOT NULL ENABLE);
 
  ALTER TABLE CUSTM_RUL_MSTR ADD CONSTRAINT UK_MRKTRULNM_CUSTMRULMSTR UNIQUE (MRKT_ID, RUL_NM)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;

