--------------------------------------------------------
--  DDL for Table MRKT_PERD_THROW_FORWRD_PRCT
--------------------------------------------------------
CREATE TABLE MRKT_PERD_THROW_FORWRD_PRCT 
   (MRKT_ID NUMBER,
    PERD_ID NUMBER,
    THROW_FORWRD_PCT NUMBER,
    CREAT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER,
    CREAT_TS DATE DEFAULT SYSDATE,
    LAST_UPDT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER,
    LAST_UPDT_TS DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &data_tablespace_name ; 

  COMMENT ON TABLE MRKT_PERD_THROW_FORWRD_PRCT  IS 'Describes master data for custom group rules';
  COMMENT ON COLUMN MRKT_PERD_THROW_FORWRD_PRCT.MRKT_ID IS 'Market';
  COMMENT ON COLUMN MRKT_PERD_THROW_FORWRD_PRCT.PERD_ID IS 'Period';
  COMMENT ON COLUMN MRKT_PERD_THROW_FORWRD_PRCT.THROW_FORWRD_PCT IS 'Throw Forward %';
  COMMENT ON COLUMN MRKT_PERD_THROW_FORWRD_PRCT.CREAT_USER_ID IS 'The user who inserted the record';
  COMMENT ON COLUMN MRKT_PERD_THROW_FORWRD_PRCT.CREAT_TS IS 'Date/timestamp of record creation';
  COMMENT ON COLUMN MRKT_PERD_THROW_FORWRD_PRCT.LAST_UPDT_USER_ID IS 'The user who last changed the record';
  COMMENT ON COLUMN MRKT_PERD_THROW_FORWRD_PRCT.LAST_UPDT_TS IS 'Date/timestamp of latest change';

--------------------------------------------------------
--  Constraints for Table MRKT_PERD_THROW_FORWRD_PRCT
--------------------------------------------------------
  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT ADD CONSTRAINT PK_MRKTPRDTHRWFRWRDPRCT PRIMARY KEY (MRKT_ID, PERD_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;

  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT ADD CONSTRAINT FK_MRKTPRDTHRWFRWRDPRCT_MP FOREIGN KEY (MRKT_ID, PERD_ID) 
  REFERENCES MRKT_PERD (MRKT_ID, PERD_ID) ENABLE;

  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT MODIFY (MRKT_ID NOT NULL ENABLE);
  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT MODIFY (PERD_ID NOT NULL ENABLE);
  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT MODIFY (THROW_FORWRD_PCT NOT NULL ENABLE);
  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT MODIFY (CREAT_USER_ID NOT NULL ENABLE);
  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT MODIFY (CREAT_TS NOT NULL ENABLE);
  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT MODIFY (LAST_UPDT_USER_ID NOT NULL ENABLE);
  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT MODIFY (LAST_UPDT_TS NOT NULL ENABLE);

  ALTER TABLE MRKT_PERD_THROW_FORWRD_PRCT ADD CONSTRAINT C_MPTFP_THRWFRWRDPRCT CHECK (THROW_FORWRD_PCT BETWEEN 0 AND 1000) ENABLE;
 