--------------------------------------------------------
--  File created - Friday-December-01-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TA_DICT
--------------------------------------------------------

  CREATE TABLE TA_DICT 
   (	LBL_ID NUMBER, 
	MRKT_ID NUMBER, 
	LBL_DESC VARCHAR2(32 BYTE), 
	LBL_WGHT NUMBER, 
	LBL_WGHT_DIR VARCHAR2(1 BYTE), 
	INT_LBL_DESC VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &data_tablespace_name ;
 

   COMMENT ON COLUMN TA_DICT.LBL_ID IS 'Label ID (OFFST_LBL_ID or SLS_TYP_LBL_ID)';
 
   COMMENT ON COLUMN TA_DICT.MRKT_ID IS 'Market ID';
 
   COMMENT ON COLUMN TA_DICT.LBL_DESC IS 'Label Description';
 
   COMMENT ON COLUMN TA_DICT.LBL_WGHT IS 'Weight used for positioning on screen';
 
   COMMENT ON COLUMN TA_DICT.LBL_WGHT_DIR IS 'Type of Entry (O - Offset, S- Sales Type)';
 
   COMMENT ON COLUMN TA_DICT.INT_LBL_DESC IS 'Internal Label Description (Label Type) - must be in(''ON-SCHEDULE'', ''OFF-SCHEDULE'', ''TRENDSETTER'', ''BI24'', ''ESTIMATE'', ''TREND'', ''ACTUAL'')';
 
   COMMENT ON TABLE TA_DICT  IS 'Trend Allocation Dictionary';
--------------------------------------------------------
--  DDL for Index PK_TA_DICT
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_TA_DICT ON TA_DICT (LBL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;
--------------------------------------------------------
--  Constraints for Table TA_DICT
--------------------------------------------------------

  ALTER TABLE TA_DICT ADD CONSTRAINT C_TA_DICT_INTLBLDESC CHECK (INT_LBL_DESC in ('ON-SCHEDULE', 'OFF-SCHEDULE', 'TRENDSETTER', 'BI24', 'ESTIMATE', 'TREND', 'ACTUAL')) ENABLE;
 
  ALTER TABLE TA_DICT ADD CONSTRAINT C_TA_DICT_LBLWGHTDIR CHECK (LBL_WGHT_DIR in ('O','S')) ENABLE;
 
  ALTER TABLE TA_DICT ADD CONSTRAINT PK_TA_DICT PRIMARY KEY (LBL_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;
 
  ALTER TABLE TA_DICT MODIFY (LBL_ID NOT NULL ENABLE);
 
  ALTER TABLE TA_DICT MODIFY (LBL_DESC NOT NULL ENABLE);
 
  ALTER TABLE TA_DICT MODIFY (LBL_WGHT NOT NULL ENABLE);
 
  ALTER TABLE TA_DICT MODIFY (LBL_WGHT_DIR NOT NULL ENABLE);
