-- DROP TABLE TEMP_CONFIG;
CREATE GLOBAL TEMPORARY TABLE TEMP_CONFIG
 (
  SRC_SLS_TYP_ID	  NUMBER,
  X_SRC_SLS_TYP_ID  NUMBER,
  OFFST_LBL_ID	    NUMBER,
  SLS_TYP_LBL_ID	  NUMBER,
  X_SLS_TYP_LBL_ID  NUMBER,
  SRC_SLS_PERD_ID	  NUMBER,
  TRGT_SLS_PERD_ID  NUMBER,
  SRC_OFFR_PERD_ID  NUMBER,
  TRGT_OFFR_PERD_ID	NUMBER,
  R_FACTOR	        NUMBER,
  SLS_TYP_GRP_NM    VARCHAR2(20 BYTE)
  )
ON COMMIT PRESERVE ROWS;