--------------------------------------------------------
--  File created - Wednesday-November-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TREND_ALLOC_HIST_DTLS
--------------------------------------------------------

  CREATE TABLE TREND_ALLOC_HIST_DTLS 
   (	MRKT_ID NUMBER, 
	SLS_PERD_ID NUMBER, 
	SLS_TYP_ID NUMBER, 
	SLS_TYP_GRP_NM VARCHAR2(128 BYTE), 
	BILNG_DAY DATE, 
	SKU_ID NUMBER, 
	VEH_ID NUMBER, 
	OFFR_ID NUMBER, 
	PROMTN_ID NUMBER, 
	PROMTN_CLM_ID NUMBER, 
	SLS_CLS_CD VARCHAR2(5 BYTE), 
	OFFST_LBL_ID NUMBER, 
	CASH_VALUE NUMBER, 
	R_FACTOR NUMBER, 
	SLS_TYP_LBL_ID NUMBER, 
	UNITS NUMBER, 
	SALES NUMBER, 
	PERD_PART NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &data_tablespace_name ;
--------------------------------------------------------
--  DDL for Index IX_TREND_ALLOC_HIST_DTLS
--------------------------------------------------------

  CREATE INDEX IX_TREND_ALLOC_HIST_DTLS ON TREND_ALLOC_HIST_DTLS (MRKT_ID, SLS_PERD_ID, SLS_TYP_ID, BILNG_DAY) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;
--------------------------------------------------------
--  Constraints for Table TREND_ALLOC_HIST_DTLS
--------------------------------------------------------

  ALTER TABLE TREND_ALLOC_HIST_DTLS MODIFY (MRKT_ID NOT NULL ENABLE);
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS MODIFY (SLS_PERD_ID NOT NULL ENABLE);
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS MODIFY (SLS_TYP_ID NOT NULL ENABLE);
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS MODIFY (SLS_TYP_GRP_NM NOT NULL ENABLE);
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS MODIFY (BILNG_DAY NOT NULL ENABLE);

