--------------------------------------------------------
--  File created - Wednesday-November-29-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TREND_ALLOC_HIST_DTLS_LOG
--------------------------------------------------------

  CREATE TABLE TREND_ALLOC_HIST_DTLS_LOG 
   (	MRKT_ID NUMBER, 
	SLS_PERD_ID NUMBER, 
	SLS_TYP_ID NUMBER, 
	BILNG_DAY DATE, 
	SLS_TYP_GRP_NM VARCHAR2(128 BYTE), 
	LAST_UPDT_TS DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &data_tablespace_name ;
--------------------------------------------------------
--  DDL for Index PK_TREND_ALLOC_HIST_DTLS_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_TREND_ALLOC_HIST_DTLS_LOG ON TREND_ALLOC_HIST_DTLS_LOG (MRKT_ID, SLS_PERD_ID, SLS_TYP_ID, BILNG_DAY, SLS_TYP_GRP_NM) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name ;
--------------------------------------------------------
--  Constraints for Table TREND_ALLOC_HIST_DTLS_LOG
--------------------------------------------------------

  ALTER TABLE TREND_ALLOC_HIST_DTLS_LOG ADD CONSTRAINT PK_TREND_ALLOC_HIST_DTLS_LOG PRIMARY KEY (MRKT_ID, SLS_PERD_ID, SLS_TYP_ID, BILNG_DAY, SLS_TYP_GRP_NM)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &index_tablespace_name  ENABLE;
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS_LOG MODIFY (MRKT_ID NOT NULL ENABLE);
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS_LOG MODIFY (SLS_PERD_ID NOT NULL ENABLE);
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS_LOG MODIFY (SLS_TYP_ID NOT NULL ENABLE);
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS_LOG MODIFY (BILNG_DAY NOT NULL ENABLE);
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS_LOG MODIFY (SLS_TYP_GRP_NM NOT NULL ENABLE);
 
  ALTER TABLE TREND_ALLOC_HIST_DTLS_LOG MODIFY (LAST_UPDT_TS NOT NULL ENABLE);

