CREATE TABLE BI24_GENRTN_STATSS 
(
  MRKT_ID NUMBER NOT NULL 
, SLS_PERD_ID NUMBER NOT NULL 
, GENRTN_DAY DATE NOT NULL 
, STATS VARCHAR2(10) NOT NULL 
, CONSTRAINT PK_BI24_GENRTN_STATSS PRIMARY KEY (MRKT_ID, SLS_PERD_ID)
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_BI24_GENRTN_STATSS ON BI24_GENRTN_STATSS(MRKT_ID ASC, SLS_PERD_ID ASC) 
      TABLESPACE &index_tablespace_name 
  ) ENABLE,
  CONSTRAINT FK_MRKT_PERD_BI24GENSTATSS FOREIGN KEY(MRKT_ID, SLS_PERD_ID)
	REFERENCES MRKT_PERD(MRKT_ID, PERD_ID) ENABLE
) 
TABLESPACE &data_tablespace_name;

COMMENT ON TABLE BI24_GENRTN_STATSS IS 'BI24 Data Generation Statuses';

COMMENT ON COLUMN BI24_GENRTN_STATSS.MRKT_ID IS 'Market ID';

COMMENT ON COLUMN BI24_GENRTN_STATSS.SLS_PERD_ID IS 'Sales Period ID';

COMMENT ON COLUMN BI24_GENRTN_STATSS.GENRTN_DAY IS 'Day of last generation';

COMMENT ON COLUMN BI24_GENRTN_STATSS.STATS IS 'Status of generation';
