CREATE TABLE DLY_BILNG_ADJSTMNT 
(
  DLY_BILNG_ID NUMBER NOT NULL 
, UNIT_QTY NUMBER(9,0) NOT NULL 
, CREAT_USER_ID VARCHAR2(35) NOT NULL 
, CREAT_TS DATE NOT NULL 
, LAST_UPDT_USER_ID VARCHAR2(35) 
, LAST_UPDT_TS DATE 
, CONSTRAINT PK_DLY_BILNG_ADJSTMNT PRIMARY KEY 
  (
    DLY_BILNG_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_DLY_BILNG_ADJSTMNT ON DLY_BILNG_ADJSTMNT (DLY_BILNG_ID ASC) 
      TABLESPACE &index_tablespace_name 
  )
  ENABLE 
) 
TABLESPACE &data_tablespace_name;

COMMENT ON TABLE DLY_BILNG_ADJSTMNT IS 'Daily Billing Adjustment';

COMMENT ON COLUMN DLY_BILNG_ADJSTMNT.DLY_BILNG_ID IS 'Daily Billing Id';

COMMENT ON COLUMN DLY_BILNG_ADJSTMNT.UNIT_QTY IS 'Adjusted Unit Qty';

COMMENT ON COLUMN DLY_BILNG_ADJSTMNT.CREAT_USER_ID IS 'User who created the record';

COMMENT ON COLUMN DLY_BILNG_ADJSTMNT.CREAT_TS IS 'Timestamp the record was created';

COMMENT ON COLUMN DLY_BILNG_ADJSTMNT.LAST_UPDT_USER_ID IS 'User who last updated the record';

COMMENT ON COLUMN DLY_BILNG_ADJSTMNT.LAST_UPDT_TS IS 'Timestamp the record was last updated';
