CREATE TABLE PK_MRKT_PERD_SKU_BIAS 
   ( MRKT_ID NUMBER NOT NULL 
   , SLS_PERD_ID NUMBER NOT NULL
   , SKU_ID NUMBER NOT NULL
   , BIAS_PCT NUMBER(6,2) NOT NULL
   , CREAT_USER_ID VARCHAR2(35 BYTE) NOT NULL
   , CREAT_TS DATE NOT NULL
   , LAST_UPDT_USER_ID VARCHAR2(35 BYTE) NOT NULL
   , LAST_UPDT_TS DATE NOT NULL
   , 
	 CONSTRAINT PK_MRKT_PERD_SKU_BIAS PRIMARY KEY (MRKT_ID, SLS_PERD_ID, SKU_ID)
     USING INDEX 
     (
      CREATE UNIQUE INDEX PK_MRKT_PERD_SKU_BIAS ON PK_MRKT_PERD_SKU_BIAS (MRKT_ID ASC, SLS_PERD_ID ASC, SKU_ID ASC) 
      TABLESPACE &index_tablespace_name 
     ) ENABLE, 
	 CONSTRAINT MRKT_PERD_SKU_BIAS_CHK1 CHECK (BIAS_PCT between 0 and 1000) ENABLE, 
	 CONSTRAINT FK_MRKTPERD_MRKTPERDSKUBIAS FOREIGN KEY (MRKT_ID, SLS_PERD_ID)
	  REFERENCES MRKT_PERD (MRKT_ID, PERD_ID) ENABLE, 
	 CONSTRAINT FK_MRKTSKU_MRKTPERDSKUBIAS FOREIGN KEY (MRKT_ID, SKU_ID)
	  REFERENCES MRKT_SKU (MRKT_ID, SKU_ID) ENABLE
   )
  TABLESPACE &data_tablespace_name ;

   COMMENT ON TABLE PK_MRKT_PERD_SKU_BIAS IS 'Market Period SKU BIAS';

   COMMENT ON COLUMN MRKT_PERD_SKU_BIAS.MRKT_ID IS 'Market ID';
   COMMENT ON COLUMN MRKT_PERD_SKU_BIAS.SLS_PERD_ID IS 'Target Sales Campaign';
   COMMENT ON COLUMN MRKT_PERD_SKU_BIAS.SKU_ID IS 'SKU ID';
   COMMENT ON COLUMN MRKT_PERD_SKU_BIAS.BIAS_PCT IS 'Bias percentage to be applied';
   COMMENT ON COLUMN MRKT_PERD_SKU_BIAS.CREAT_USER_ID IS 'The user who inserted the record';
   COMMENT ON COLUMN MRKT_PERD_SKU_BIAS.CREAT_TS IS 'Date/timestamp of record creation';
   COMMENT ON COLUMN MRKT_PERD_SKU_BIAS.LAST_UPDT_USER_ID IS 'The user who last changed the record';
   COMMENT ON COLUMN MRKT_PERD_SKU_BIAS.LAST_UPDT_TS IS 'Date/timestamp of latest change';