CREATE TABLE SCT_FSC_OVRRD 
(
  MRKT_ID NUMBER NOT NULL 
, SLS_PERD_ID NUMBER NOT NULL 
, SLS_TYP_ID NUMBER NOT NULL 
, FSC_CD VARCHAR2(8) NOT NULL 
, SCT_UNIT_QTY NUMBER NOT NULL 
, CREAT_USER_ID VARCHAR2(35) DEFAULT USER NOT NULL 
, CREAT_TS DATE DEFAULT SYSDATE NOT NULL 
, LAST_UPDT_USER_ID VARCHAR2(35) DEFAULT USER NOT NULL 
, LAST_UPDT_TS DATE DEFAULT SYSDATE NOT NULL 
, CONSTRAINT PK_SCT_FSC_OVRRD PRIMARY KEY (MRKT_ID, SLS_PERD_ID, SLS_TYP_ID)
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_SCT_FSC_OVRRD ON SCT_FSC_OVRRD (MRKT_ID ASC, SLS_PERD_ID ASC, SLS_TYP_ID ASC) 
      TABLESPACE &index_tablespace_name 
  ) ENABLE,
  CONSTRAINT FK_MRKTPERD_SCTFSCOVRRD FOREIGN KEY (MRKT_ID, SLS_PERD_ID)
   REFERENCES MRKT_PERD (MRKT_ID, PERD_ID) ENABLE,
  CONSTRAINT FK_MRKT_SCTFSCOVRRD FOREIGN KEY ( MRKT_ID )
   REFERENCES MRKT ( MRKT_ID ) ENABLE,
  CONSTRAINT FK_SLSTYP_SCTFSCOVRRD FOREIGN KEY ( SLS_TYP_ID )
   REFERENCES SLS_TYP ( SLS_TYP_ID ) ENABLE 
) 
TABLESPACE &data_tablespace_name;

COMMENT ON TABLE SCT_FSC_OVRRD IS 'Trend offset - stores trend offset values counted by Market_ID and Trend Type.';

COMMENT ON COLUMN SCT_FSC_OVRRD.MRKT_ID IS 'Market Id';

COMMENT ON COLUMN SCT_FSC_OVRRD.SLS_PERD_ID IS 'Target Sales Campaign';

COMMENT ON COLUMN SCT_FSC_OVRRD.SLS_TYP_ID IS 'Trend Type';

COMMENT ON COLUMN SCT_FSC_OVRRD.FSC_CD IS 'FSC Code';

COMMENT ON COLUMN SCT_FSC_OVRRD.SCT_UNIT_QTY IS 'Total Trend Units to be recorded for this FSC in the specified Market/Campaign';

COMMENT ON COLUMN SCT_FSC_OVRRD.CREAT_USER_ID IS 'User who created the record';

COMMENT ON COLUMN SCT_FSC_OVRRD.CREAT_TS IS 'Timestamp the record was created';

COMMENT ON COLUMN SCT_FSC_OVRRD.LAST_UPDT_USER_ID IS 'User who last updated the record';

COMMENT ON COLUMN SCT_FSC_OVRRD.LAST_UPDT_TS IS 'Timestamp the record was last updated';
