ALTER TABLE MRKT_SLS_PERD
ADD CONSTRAINT FK_MRKTPERD_MRKTSLSPERD FOREIGN KEY
(
  MRKT_ID 
, SLS_PERD_ID 
)
REFERENCES MRKT_PERD
(
  MRKT_ID 
, PERD_ID 
)
ENABLE;

ALTER TABLE MRKT_SLS_PERD
ADD CONSTRAINT C_MSP_SLSPERDID CHECK 
(SLS_PERD_ID >= 20050301)
ENABLE;