CREATE INDEX FK_MRKTPERD_MRKTPERDSKUBIAS ON MRKT_PERD_SKU_BIAS (MRKT_ID, SLS_PERD_ID) 
TABLESPACE &index_tablespace_name;

CREATE INDEX FK_MRKTSKU_MRKTPERDSKUBIAS ON MRKT_PERD_SKU_BIAS (MRKT_ID, SKU_ID) 
TABLESPACE &index_tablespace_name;

