CREATE INDEX FK_MRKTPERD_TRENDOFFST ON TREND_OFFST (MRKT_ID, EFF_SLS_PERD_ID) 
TABLESPACE &index_tablespace_name;

CREATE INDEX FK_MRKT_TRENDOFFST ON TREND_OFFST (MRKT_ID) 
TABLESPACE &index_tablespace_name;

CREATE INDEX FK_SLSTYP_TRENDOFFST ON TREND_OFFST (SLS_TYP_ID) 
TABLESPACE &index_tablespace_name;

