insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 6, null, null, 100, 'ACTUAL', 1006, null, null, 1, null, 1, 'H', null, 3, 'config for ACTUAL (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DBT_OSL', 6, null, null, 100, 'BI24', 900, 901, 0, null, 1, null, 'H', null, 3, 'config for BI24 (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 2, null, null, 100, 'ESTIMATE', 1002, null, null, 1, null, 1, 'H', null, 3, 'config for ESTIMATE (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DBT_OSL', 6, 'DMS', 1, 100, 'FORECASTED_DBT', 1003, 901, 0, 1, 1, 1, 'A', null, 3, 'config for Trend Calculation (On-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names: 
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 3, null, null, 100, 'TREND', 1003, null, null, 1, null, 1, 'H', null, 3, 'config for EST (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 6, null, null, 300, 'ACTUAL', 1006, null, null, 1, null, 2, 'H', null, 3, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 2, null, null, 300, 'ESTIMATE', 1002, null, null, 2, null, 2, 'H', null, 3, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 2, null, null, 300, 'FORECASTED_DMS', 1003, 901, null, 1, null, 2, 'A', 0.05, 3, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 3, null, null, 300, 'TREND', 1003, null, null, 1, null, 2, 'H', null, 3, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DBT_OSL', 6, 'DMS', 1, 100, 'FORECASTED_DBT', 1004, 901, 0, 0, 0, 0, 'A', null, 4, 'config for Trend Calculation (On-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names: 
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 4, null, null, 100, 'TREND', 1004, null, null, 0, null, 0, 'H', null, 4, 'config for BST (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DBT_OSL', 6, 'DMS', 1, 200, 'FORECASTED_DBT', 1004, 901, 0, 0, -1, -1, 'A', null, 4, 'config for Trend Calculation (Off-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names: 
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 4, null, null, 200, 'TREND', 1004, null, null, 0, null, -1, 'H', null, 4, 'config for BST (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 2, null, null, 300, 'FORECASTED_DMS', 1004, 901, null, 0, null, 2, 'A', 0.05, 4, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 4, null, null, 300, 'TREND', 1004, null, null, 0, null, 2, 'H', null, 4, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 5, null, null, 100, 'TREND', 1005, null, null, 0, null, 0, 'H', null, 5, 'config for FDT (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 5, null, null, 200, 'TREND', 1005, null, null, 0, null, -1, 'H', null, 5, 'config for FDT (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 5, null, null, 300, 'TREND', 1005, null, null, 0, null, 2, 'H', null, 5, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DBT_OSL', 6, 'DMS', 1, 100, 'FORECASTED_DBT', 1003, 901, 0, 1, 1, 1, 'A', null, 103, 'config for Trend Calculation (On-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names: 
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 103, null, null, 100, 'TREND', 1003, null, null, 1, null, 1, 'H', null, 103, 'config for EST (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 2, null, null, 300, 'FORECASTED_DMS', 1003, 901, null, 1, null, 2, 'A', 0.05, 103, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 103, null, null, 300, 'TREND', 1003, null, null, 1, null, 2, 'H', null, 103, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DBT_OSL', 6, 'DMS', 1, 100, 'FORECASTED_DBT', 1004, 901, 0, 0, 0, 0, 'A', null, 104, 'config for Trend Calculation (On-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names: 
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 104, null, null, 100, 'TREND', 1004, null, null, 0, null, 0, 'H', null, 104, 'config for BST (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DBT_OSL', 6, 'DMS', 1, 200, 'FORECASTED_DBT', 1004, 901, 0, 0, -1, -1, 'A', null, 104, 'config for Trend Calculation (Off-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names: 
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 104, null, null, 200, 'TREND', 1004, null, null, 0, null, -1, 'H', null, 104, 'config for BST (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 2, null, null, 300, 'FORECASTED_DMS', 1004, 901, null, 0, null, 2, 'A', 0.05, 104, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 104, null, null, 300, 'TREND', 1004, null, null, 0, null, 2, 'H', null, 104, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 105, null, null, 100, 'TREND', 1005, null, null, 0, null, 0, 'H', null, 105, 'config for FDT (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 105, null, null, 200, 'TREND', 1005, null, null, 0, null, -1, 'H', null, 105, 'config for FDT (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (50, 20100301, 'DMS', 105, null, null, 300, 'TREND', 1005, null, null, 0, null, 2, 'H', null, 105, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 100, 'ACTUAL', 1006, null, null, 2, null, 2, 'H', null, 3, 'config for ACTUAL (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 100, 'BI24', 900, 901, 0, null, 2, null, 'H', null, 3, 'config for BI24 (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 100, 'ESTIMATE', 1002, null, null, 2, null, 2, 'H', null, 3, 'config for ESTIMATE (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, 'DMS', 1, 100, 'FORECASTED_DBT', 1003, 901, 0, 2, 2, 2, 'A', null, 3, 'config for Trend Calculation (On-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names:
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 3, null, null, 100, 'TREND', 1003, null, null, 2, null, 2, 'H', null, 3, 'config for EST (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 200, 'ACTUAL', 1006, null, null, 2, null, 1, 'H', null, 3, 'config for ACTUAL (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 200, 'BI24', 900, 901, 0, null, 1, null, 'H', null, 3, 'config for BI24 (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 200, 'ESTIMATE', 1002, null, null, 2, null, 1, 'H', null, 3, 'config for ESTIMATE (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, 'DMS', 1, 200, 'FORECASTED_DBT', 1003, 901, 0, 2, 1, 1, 'A', null, 3, 'config for Trend Calculation (Off-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names:
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 3, null, null, 200, 'TREND', 1003, null, null, 2, null, 1, 'H', null, 3, 'config for EST (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 400, 'ACTUAL', 1006, null, null, 2, null, 3, 'H', null, 3, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 400, 'ESTIMATE', 1002, null, null, 3, null, 3, 'H', null, 3, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 400, 'FORECASTED_DMS', 1003, 901, null, 2, null, 3, 'A', 0.0001, 3, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 3, null, null, 400, 'TREND', 1003, null, null, 3, null, 3, 'H', null, 3, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 100, 'ACTUAL', 1006, null, null, 0, null, 0, 'H', null, 4, 'config for ACTUAL (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 100, 'BI24', 900, 901, 0, null, 0, null, 'H', null, 4, 'config for BI24 (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 100, 'ESTIMATE', 1002, null, null, 0, null, 0, 'H', null, 4, 'config for ESTIMATE (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, 'DMS', 1, 100, 'FORECASTED_DBT', 1004, 901, 0, 0, 0, 0, 'A', null, 4, 'config for Trend Calculation (On-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names:
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 4, null, null, 100, 'TREND', 1004, null, null, 0, null, 0, 'H', null, 4, 'config for BST (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 200, 'ACTUAL', 1006, null, null, 0, null, -1, 'H', null, 4, 'config for ACTUAL (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 200, 'BI24', 900, 901, 0, null, -1, null, 'H', null, 4, 'config for BI24 (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 200, 'ESTIMATE', 1002, null, null, 0, null, -1, 'H', null, 4, 'config for ESTIMATE (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, 'DMS', 1, 200, 'FORECASTED_DBT', 1004, 901, 0, 0, -1, -1, 'A', null, 4, 'config for Trend Calculation (Off-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names:
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 4, null, null, 200, 'TREND', 1004, null, null, 0, null, -1, 'H', null, 4, 'config for BST (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 300, 'ACTUAL', 1006, null, null, 0, null, 2, 'H', null, 4, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 300, 'BI24', 900, 901, 0, null, 2, null, 'H', null, 4, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 300, 'ESTIMATE', 1002, null, null, 0, null, 2, 'H', null, 4, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 300, 'FORECASTED_DMS', 1004, 901, null, 0, null, 2, 'A', null, 4, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 4, null, null, 300, 'TREND', 1004, null, null, 0, null, 2, 'H', null, 4, null);

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 100, 'ACTUAL', 1006, null, null, 0, null, 0, 'H', null, 5, 'config for ACTUAL (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 100, 'BI24', 900, 901, 0, null, 0, null, 'H', null, 5, 'config for BI24 (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 100, 'ESTIMATE', 1002, null, null, 0, null, 0, 'H', null, 5, 'config for ESTIMATE (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 5, null, null, 100, 'TREND', 1005, null, null, 0, null, 0, 'H', null, 5, 'config for FDT (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 200, 'ACTUAL', 1006, null, null, 0, null, -1, 'H', null, 5, 'config for ACTUAL (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 200, 'BI24', 900, 901, 0, null, -1, null, 'H', null, 5, 'config for BI24 (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 200, 'ESTIMATE', 1002, null, null, 0, null, -1, 'H', null, 5, 'config for ESTIMATE (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 5, null, null, 200, 'TREND', 1005, null, null, 0, null, -1, 'H', null, 5, 'config for FDT (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 100, 'ACTUAL', 1006, null, null, 2, null, 2, 'H', null, 103, 'config for ACTUAL (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 100, 'BI24', 900, 901, 0, null, 2, null, 'H', null, 103, 'config for BI24 (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 100, 'ESTIMATE', 1002, null, null, 2, null, 2, 'H', null, 103, 'config for ESTIMATE (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, 'DMS', 1, 100, 'FORECASTED_DBT', 1003, 901, 0, 2, 2, 2, 'A', null, 103, 'config for Trend Calculation (On-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names:
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 103, null, null, 100, 'TREND', 1003, null, null, 2, null, 2, 'H', null, 103, 'config for EST (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 200, 'ACTUAL', 1006, null, null, 2, null, 1, 'H', null, 103, 'config for ACTUAL (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 200, 'BI24', 900, 901, 0, null, 1, null, 'H', null, 103, 'config for BI24 (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 200, 'ESTIMATE', 1002, null, null, 2, null, 1, 'H', null, 103, 'config for ESTIMATE (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, 'DMS', 1, 200, 'FORECASTED_DBT', 1003, 901, 0, 2, 1, 1, 'A', null, 103, 'config for Trend Calculation (Off-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names:
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 103, null, null, 200, 'TREND', 1003, null, null, 2, null, 1, 'H', null, 103, 'config for EST (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 100, 'ACTUAL', 1006, null, null, 0, null, 0, 'H', null, 104, 'config for ACTUAL (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 100, 'BI24', 900, 901, 0, null, 0, null, 'H', null, 104, 'config for BI24 (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 100, 'ESTIMATE', 1002, null, null, 0, null, 0, 'H', null, 104, 'config for ESTIMATE (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, 'DMS', 1, 100, 'FORECASTED_DBT', 1004, 901, 0, 0, 0, 0, 'A', null, 104, 'config for Trend Calculation (On-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names:
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 104, null, null, 100, 'TREND', 1004, null, null, 0, null, 0, 'H', null, 104, 'config for BST (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 200, 'ACTUAL', 1006, null, null, 0, null, -1, 'H', null, 104, 'config for ACTUAL (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 200, 'BI24', 900, 901, 0, null, -1, null, 'H', null, 104, 'config for BI24 (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 200, 'ESTIMATE', 1002, null, null, 0, null, -1, 'H', null, 104, 'config for ESTIMATE (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, 'DMS', 1, 200, 'FORECASTED_DBT', 1004, 901, 0, 0, -1, -1, 'A', null, 104, 'config for Trend Calculation (Off-schedule):
BI24 (input: src_sls_typ_id) used in get_reproc_trnd function
and
ESTIMATE (input: est_src_sls_typ_id) used in get_reproc_est function

output column names:
x_sls_typ_lbl_id (for INPUT values)
sls_typ_lbl_id   (for FORCASTED TREND values)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 104, null, null, 200, 'TREND', 1004, null, null, 0, null, -1, 'H', null, 104, 'config for BST (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 100, 'ACTUAL', 1006, null, null, 0, null, 0, 'H', null, 105, 'config for ACTUAL (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 100, 'BI24', 900, 901, 0, null, 0, null, 'H', null, 105, 'config for BI24 (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 100, 'ESTIMATE', 1002, null, null, 0, null, 0, 'H', null, 105, 'config for ESTIMATE (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 105, null, null, 100, 'TREND', 1005, null, null, 0, null, 0, 'H', null, 105, 'config for FDT (On-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 6, null, null, 200, 'ACTUAL', 1006, null, null, 0, null, -1, 'H', null, 105, 'config for ACTUAL (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DBT_OSL', 6, null, null, 200, 'BI24', 900, 901, 0, null, -1, null, 'H', null, 105, 'config for BI24 (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 2, null, null, 200, 'ESTIMATE', 1002, null, null, 0, null, -1, 'H', null, 105, 'config for ESTIMATE (Off-schedule)');

insert into TA_CONFIG (MRKT_ID, EFF_SLS_PERD_ID, SRC_TABLE, SRC_SLS_TYP_ID, EST_SRC_TABLE, EST_SRC_SLS_TYP_ID, OFFST_LBL_ID, SLS_TYP_GRP_NM, SLS_TYP_LBL_ID, X_SLS_TYP_LBL_ID, OFFST_VAL_SRC_SLS, OFFST_VAL_TRGT_SLS, OFFST_VAL_SRC_OFFR, OFFST_VAL_TRGT_OFFR, GRID_TYP, R_FACTOR, TRGT_SLS_TYP_ID, COMMNT)
values (73, 20100301, 'DMS', 105, null, null, 200, 'TREND', 1005, null, null, 0, null, -1, 'H', null, 105, 'config for FDT (Off-schedule)');
