INSERT INTO TREND_OFFST
	(MRKT_ID, EFF_SLS_PERD_ID, SLS_TYP_ID, OFFST)
	SELECT MRKT_ID,
				 EFF_SLS_PERD_ID,
				 SLS_TYP_ID,
				 case when SLS_TYP_ID in (3,103)
				      then CASE WHEN M_CNTRY_CD = 'UK' and SLS_TYP_ID = 3 THEN 2
						        ELSE 1
					  else 0
			     END OFFST
		FROM (SELECT SLS_TYP_ID, SLS_TYP_NM
						FROM SLS_TYP_GRP
						JOIN SLS_TYP
					 USING (SLS_TYP_GRP_ID)
					 WHERE SLS_TYP_GRP_DESC_TXT = 'Trend') TRT,
				 (SELECT MRKT_ID,
								 MIN(PERD_ID) EFF_SLS_PERD_ID,
								 MAX(CNTRY_CD) M_CNTRY_CD
						FROM MRKT_PERD
						JOIN MRKT
					 USING (MRKT_ID)
					 WHERE PERD_ID >= 20000301
					 GROUP BY MRKT_ID) MPL;

