insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (100, null, 'On-Schedule', 2000, 'O', 'ON-SCHEDULE');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (200, null, 'Off-Schedule', 1000, 'O', 'OFF-SCHEDULE');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (300, null, 'Trendsetter', 3000, 'O', 'TRENDSETTER');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (400, null, 'Trendsetter-2', 4000, 'O', 'TRENDSETTER-2');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (900, null, 'BI24', 13500, 'S', 'BI24');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (901, null, 'INPUT SALES DATA', 13400, 'S', 'BI24');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (1001, null, 'ESTIMATE', 12500, 'S', 'ESTIMATE');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (1002, null, 'OPERATIONAL ESTIMATE', 12400, 'S', 'ESTIMATE');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (1003, null, 'EARLY SELLING TREND', 11403, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (1004, null, 'BILLED SALES TREND', 11404, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (1005, null, 'FINAL DAY TREND', 11405, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (1006, null, 'ACTUAL', 10500, 'S', 'ACTUAL');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (1103, null, 'EST FOR SCT', 11413, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (1104, null, 'BST FOR SCT', 11414, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (1105, null, 'FDT FOR SCT', 11415, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (50900, null, 'BI24', 13500, 'S', 'BI24');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (50950, null, 'SHIPPED_TO_DATE', 13450, 'S', 'BI24');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (501001, null, 'ESTIMATE', 12500, 'S', 'ESTIMATE');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (501002, null, 'OPERATIONAL ESTIMATE', 12400, 'S', 'ESTIMATE');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (501003, null, 'EARLY SELLING TREND', 11403, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (501004, null, 'BILLED SALES TREND', 11404, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (501005, null, 'FINAL DAY TREND', 11405, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (501103, null, 'EST FOR SCT', 11413, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (501104, null, 'BST FOR SCT', 11414, 'S', 'TREND');
insert into TA_DICT (LBL_ID, MRKT_ID, LBL_DESC, LBL_WGHT, LBL_WGHT_DIR, INT_LBL_DESC)
values (501105, null, 'FDT FOR SCT', 11415, 'S', 'TREND');
