CREATE TABLE TA_DICT 
(
  LBL_ID NUMBER NOT NULL 
, MRKT_ID NUMBER 
, LBL_DESC VARCHAR2(32) NOT NULL 
, LBL_WGHT NUMBER NOT NULL 
, LBL_WGHT_DIR VARCHAR2(1) NOT NULL 
, CONSTRAINT PK_TA_DICT PRIMARY KEY 
  (
    LBL_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TA_DICT ON TA_DICT (LBL_ID ASC) 
      TABLESPACE &index_tablespace_name 
  )
  ENABLE 
) 
TABLESPACE &data_tablespace_name;

ALTER TABLE TA_DICT
ADD CONSTRAINT C_TA_DICT_LBLWGHTDIR CHECK 
(LBL_WGHT_DIR in ('O','S'))
ENABLE;

COMMENT ON TABLE TA_DICT IS 'Trend Allocation Dictionary';

COMMENT ON COLUMN TA_DICT.LBL_ID IS 'Label ID';

COMMENT ON COLUMN TA_DICT.MRKT_ID IS 'Market ID';

COMMENT ON COLUMN TA_DICT.LBL_DESC IS 'Label Description';

COMMENT ON COLUMN TA_DICT.LBL_WGHT IS 'Weight used for positioning on screen';

COMMENT ON COLUMN TA_DICT.LBL_WGHT_DIR IS 'Direction of ordering (R - Row, C- Column)';
