CREATE TABLE TREND_ALLOC_HIST_DTLS_LOG 
(
  MRKT_ID NUMBER NOT NULL 
, SLS_PERD_ID NUMBER NOT NULL 
, SLS_TYP_ID NUMBER NOT NULL 
, SLS_TYP_GRP_NM VARCHAR2(128 BYTE) NOT NULL 
, BILNG_DAY DATE NOT NULL 
, LAST_UPDT_TS DATE NOT NULL 
, CONSTRAINT PK_TREND_ALLOC_HIST_DTLS_LOG PRIMARY KEY 
  ( MRKT_ID, SLS_PERD_ID, SLS_TYP_ID, SLS_TYP_GRP_NM, BILNG_DAY)
  USING INDEX 
  ( CREATE UNIQUE INDEX PK_TREND_ALLOC_HIST_DTLS_LOG ON TREND_ALLOC_HIST_DTLS_LOG (MRKT_ID ASC, SLS_PERD_ID ASC, SLS_TYP_ID ASC, SLS_TYP_GRP_NM ASC, BILNG_DAY ASC) 
    TABLESPACE &index_tablespace_name 
  )
  ENABLE 
) 
TABLESPACE &data_tablespace_name; 

