CREATE TABLE TREND_OFFST 
(
  MRKT_ID NUMBER NOT NULL 
, EFF_SLS_PERD_ID NUMBER NOT NULL 
, SLS_TYP_ID NUMBER NOT NULL 
, OFFST NUMBER NOT NULL 
, CREAT_USER_ID VARCHAR2(35) DEFAULT USER NOT NULL 
, CREAT_TS DATE DEFAULT SYSDATE NOT NULL NOT NULL 
, LAST_UPDT_USER_ID VARCHAR2(35) DEFAULT USER NOT NULL 
, LAST_UPDT_TS DATE DEFAULT SYSDATE NOT NULL 
, CONSTRAINT PK_TREND_OFFST PRIMARY KEY (MRKT_ID, EFF_SLS_PERD_ID, SLS_TYP_ID)
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TREND_OFFST ON TREND_OFFST (MRKT_ID ASC, EFF_SLS_PERD_ID ASC, SLS_TYP_ID ASC) 
      TABLESPACE &index_tablespace_name 
  ) ENABLE,
  CONSTRAINT FK_MRKTPERD_TRENDOFFST FOREIGN KEY (MRKT_ID, EFF_SLS_PERD_ID)
   REFERENCES MRKT_PERD (MRKT_ID, PERD_ID) ENABLE,
  CONSTRAINT FK_MRKT_TRENDOFFST FOREIGN KEY ( MRKT_ID )
   REFERENCES MRKT ( MRKT_ID ) ENABLE,
  CONSTRAINT FK_SLSTYP_TRENDOFFST FOREIGN KEY ( SLS_TYP_ID )
   REFERENCES SLS_TYP ( SLS_TYP_ID ) ENABLE 
) 
TABLESPACE &data_tablespace_name;

COMMENT ON TABLE TREND_OFFST IS 'Trend offset - stores trend offset values counted by Market_ID and Trend Type.';

COMMENT ON COLUMN TREND_OFFST.MRKT_ID IS 'Market Id';

COMMENT ON COLUMN TREND_OFFST.EFF_SLS_PERD_ID IS 'Effective Sales Campaign';

COMMENT ON COLUMN TREND_OFFST.SLS_TYP_ID IS 'Trend Type';

COMMENT ON COLUMN TREND_OFFST.OFFST IS 'Offset Value';

COMMENT ON COLUMN TREND_OFFST.CREAT_USER_ID IS 'User who created the record';

COMMENT ON COLUMN TREND_OFFST.CREAT_TS IS 'Timestamp the record was created';

COMMENT ON COLUMN TREND_OFFST.LAST_UPDT_USER_ID IS 'User who last updated the record';

COMMENT ON COLUMN TREND_OFFST.LAST_UPDT_TS IS 'Timestamp the record was last updated';
