@Types\OBJ_MANL_TREND_UPLOAD_LINE.sql
@Types\OBJ_MANL_TREND_UPLOAD_TABLE.sql
@Types\OBJ_MANL_TREND_UPL_SAVE_LINE.sql
@Types\OBJ_MANL_TREND_UPL_SAVE_TABLE.sql
@Types\OBJ_MANL_TREND_UPL_DEL_LINE.sql
@Types\OBJ_MANL_TREND_UPL_DEL_TABLE.sql

@Tables\MANUAL_TREND_UPLOAD.sql

@Packages\PA_MANUAL_TREND_UPLOAD.sql
show errors

@Packages\PA_MANUAL_TREND_UPLOAD_body.sql
show errors
