ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_ALOCTN_END_TS;

ALTER TABLE MRKT_SLS_PERD 
NOCOMPRESS

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_CASH_VAL;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_R_FACTOR;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_PRCSNG_DT;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_ALOCTN_USER_ID;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_ALOCTN_STRT_TS;

ALTER TABLE MRKT_SLS_PERD 
DROP COLUMN SCT_ALOCTN_END_TS;

ALTER TABLE MRKT_SLS_PERD 
COMPRESS