ALTER TABLE MRKT_SLS_PERD
DROP CONSTRAINT FK_MRKTPERD_MRKTSLSPERD;

ALTER TABLE MRKT_SLS_PERD
DROP CONSTRAINT C_MSP_SCTAUTCLCBSTIND;

ALTER TABLE MRKT_SLS_PERD
DROP CONSTRAINT C_MSP_SCTAUTCLCESTIND;

