--------------------------------------------------------
--  File created - péntek-március-03-2017   
--------------------------------------------------------
REM INSERTING into TA_DICT
SET DEFINE OFF;
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('100',null,'On-Schedule','2000','O');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('200',null,'Off-Schedule','1000','O');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('300',null,'Trendsetter','3000','O');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('400',null,'Trendsetter-2','4000','O');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('1000',null,'BI24','13500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('73001','73','TREND','11500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('73002','73','ACTUAL','10500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('73003','73','ESTIMATE','12500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('50001','50','TENDENZA','11500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('50003','50','STIMATO','12500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('50002','50','EFFETTIVO','10500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('68002','68','REAL','10500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('68003','68','TENDENCIA','11500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('68001','68','ESTIMADO','12500','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('1004',null,'OPERATIONAL ESTIMATE','12400','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('1005',null,'EARLY SELLING TREND','11403','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('1006',null,'BILLED SALES TREND','11404','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('1007',null,'FINAL DAY TREND','11405','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('1008',null,'EST FOR SCT','11413','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('1009',null,'BST FOR SCT','11414','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('1010',null,'FDT FOR SCT','11415','S');
Insert into TA_DICT (LBL_ID,MRKT_ID,LBL_DESC,LBL_WGHT,LBL_WGHT_DIR) values ('1001',null,'INPUT SALES DATA','13400','S');
