set serveroutput on;

DECLARE
  a FS_MRKT_PRFL_BNCHMRK_SYNC.FS_MRKT_PRFL_BNCHMRK_LINE;
--  b FS_MRKT_PRFL_BNCHMRK_LINE;
--  c FS_MRKT_PRFL_BNCHMRK_LINE;
BEGIN
  a.MRKT_ID:=68;
  a.PRFL_CD:=7777777;
  a.EFF_PERD_ID:=20170305;
  a.BENCHMARK_DATA(1).BNCHMRK_PRFL_CD:=7777771;
  a.BENCHMARK_DATA(2).BNCHMRK_PRFL_CD:=7777772;
  a.BENCHMARK_DATA(1).DFALT_IND:='D';
  a.BENCHMARK_DATA(2).DFALT_IND:=' ';
  FS_MRKT_PRFL_BNCHMRK_SYNC.SYNC_BNCHMRK(a);
END;
