CREATE TABLE TREND_ALLOC_HIST_DTLS 
(
  MRKT_ID NUMBER NOT NULL 
, SLS_PERD_ID NUMBER NOT NULL 
, SLS_TYP_ID NUMBER NOT NULL 
, SLS_TYP_GRP_NM VARCHAR2(128 BYTE) NOT NULL 
, BILNG_DAY DATE NOT NULL 
, SKU_ID NUMBER 
, VEH_ID NUMBER 
, OFFR_ID NUMBER 
, PROMTN_ID NUMBER 
, PROMTN_CLM_ID NUMBER 
, SLS_CLS_CD VARCHAR2(5 BYTE) 
, OFFST_LBL_ID NUMBER 
, CASH_VALUE NUMBER 
, R_FACTOR NUMBER 
, SLS_TYP_LBL_ID NUMBER 
, UNITS NUMBER 
, SALES NUMBER 
) 
 
TABLESPACE &data_tablespace_name; 

CREATE INDEX IX_TREND_ALLOC_HIST_DTLS ON TREND_ALLOC_HIST_DTLS (MRKT_ID ASC, SLS_PERD_ID ASC, SLS_TYP_ID ASC, BILNG_DAY ASC) 

TABLESPACE APP_IND_WEDEV 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
