create or replace type OBJ_PA_TREND_ALLOC_SGMNT_LINE FORCE as object
(
  RUL_NM       VARCHAR2(50),
  SLS_PERD_ID  NUMBER,
  BILNG_DAY    DATE,
  ISSELECTED   CHAR(1),
  UNITS_BI24   NUMBER,
  SALES_BI24   NUMBER,
  UNITS_ACTUAL NUMBER,
  SALES_ACTUAL NUMBER
);
/
show error
