create or replace type OBJ_MRKTPRDTHRWFRWRDPRCT_LINE FORCE as object
(
  PERD_ID NUMBER,
  THROW_FORWRD_PCT NUMBER,
  LAST_UPDT_USER_ID VARCHAR2(35 BYTE),
  LAST_UPDT_TS DATE,
  CREAT_USER_ID VARCHAR2(35 BYTE),
  CREAT_TS DATE
);
/
show error
