CREATE TABLE MRKT_PERD_TYP_RULSTS 
(
  MRKT_ID NUMBER NOT NULL 
, TRG_PERD_ID NUMBER NOT NULL 
, SLS_TYP_ID NUMBER NOT NULL
, RULE_ID NUMBER DEFAULT 0 NOT NULL 
, CATGRY_ID NUMBER NOT NULL 
, BRND_ID NUMBER NOT NULL 
, SGMT_ID NUMBER NOT NULL 
, FORM_ID NUMBER NOT NULL 
, HIST_PERD_ID NUMBER NOT NULL 
, HIST_PERD_TYP VARCHAR2(1 BYTE) NOT NULL 
, R_FACTOR NUMBER NOT NULL
, CATGRY_NM VARCHAR2(100 BYTE) NOT NULL
, BRAND_NM VARCHAR2(128 BYTE) NOT NULL
, FORM_DESC_TXT VARCHAR2(128 BYTE) NOT NULL
, SGMNT_NM VARCHAR2(128 BYTE) NOT NULL
, UNITS_BI24 NUMBER NOT NULL 
, SALES_BI24 NUMBER NOT NULL 
, UNITS_ESTMT NUMBER NOT NULL 
, SALES_ESTMT NUMBER NOT NULL 
, UNITS_TRND NUMBER NOT NULL 
, SALES_TRND NUMBER NOT NULL 
, UNITS_ACTUAL NUMBER NOT NULL 
, SALES_ACTUAL NUMBER NOT NULL 
, CREAT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER NOT NULL 
, CREAT_TS DATE DEFAULT SYSDATE NOT NULL 
, LAST_UPDT_USER_ID VARCHAR2(35 BYTE) DEFAULT USER NOT NULL 
, LAST_UPDT_TS DATE DEFAULT SYSDATE NOT NULL 
, 
	 CONSTRAINT MRKT_PERD_TYP_RULSTS_CHK1 CHECK (HIST_PERD_TYP IN('O','F','T')) ENABLE, 
	 CONSTRAINT FK_MRKTPERD_MRKTPERDTYPRULSTS FOREIGN KEY (MRKT_ID, TRG_PERD_ID)
	  REFERENCES MRKT_PERD (MRKT_ID, PERD_ID) ENABLE, 
	 CONSTRAINT FK2_MRKTPERD_MRKTPERDTYPRULSTS FOREIGN KEY (MRKT_ID, HIST_PERD_ID)
	  REFERENCES MRKT_PERD (MRKT_ID, PERD_ID) ENABLE, 
	 CONSTRAINT FK_SLSTYP_MRKTPERDTYPRULSTS FOREIGN KEY (SLS_TYP_ID)
	  REFERENCES SLS_TYP (SLS_TYP_ID) ENABLE
)
TABLESPACE APP_DATA_WEDEV
;

   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."MRKT_ID" IS 'Market Id';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."TRG_PERD_ID" IS 'Target Sales Campaign';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."SLS_TYP_ID" IS 'Trend Type';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."RULE_ID" IS 'Rule Ordering Number (ID) in descending priority inside ruleset';  
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."CATGRY_ID" IS 'Category defining the rule';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."BRND_ID" IS 'Brand defining the rule';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."SGMT_ID" IS 'Segment defining the rule';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."FORM_ID" IS 'Form defining the rule';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."CATGRY_NM" IS 'Category Name';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."BRAND_NM" IS 'Brand Name';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."FORM_DESC_TXT" IS 'Form Name';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."SGMNT_NM" IS 'Segment Name';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."HIST_PERD_ID" IS 'One of historic periods used to calculate default r-factor for the specified rule';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."HIST_PERD_ID" IS 'Type of period included: on-, off schedule or trendsetter (O, F or T)';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."R_FACTOR" IS 'User defined R-factor for the rule, (-1 if the calculated value has to be used ? )';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."UNITS_BI24" IS 'BI24 Units';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."SALES_BI24" IS 'BI24 Sales';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."UNITS_ESTMT" IS 'Estimated Units';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."SALES_ESTMT" IS 'Estimated Sales';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."UNITS_TRND" IS 'Trend Units';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."SALES_TRND" IS 'Trend Sales';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."UNITS_ACTUAL" IS 'Actual Units';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."SALES_ACTUAL" IS 'Actual Sales';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."CREAT_USER_ID" IS 'User who created the record';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."CREAT_TS" IS 'Timestamp the record was created';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."LAST_UPDT_USER_ID" IS 'User who last updated the record';
   COMMENT ON COLUMN "WEDEV"."MRKT_PERD_TYP_RULSTS"."LAST_UPDT_TS" IS 'Timestamp the record was last updated';
   COMMENT ON TABLE "WEDEV"."MRKT_PERD_TYP_RULSTS"  IS 'Rulesets - stores rules used to calculate for Market_ID, Targer period, Trend Type and ID-vector.';
